version: 0.2

env:
  variables:
    AWS_REGION: "us-east-1"
    BUILD_DIR: "build"
    S3_BUCKET: poc.friender.io
    STAGE: "dev"
  parameter-store:
    AWS_ACCESS_KEY_ID: "/CodeBuild/AWS_ACCESS_KEY_ID"
    AWS_SECRET_ACCESS_KEY: "/CodeBuild/AWS_SECRET_ACCESS_KEY"

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing dependencies...
      - apt update
      - apt-get install -yq --no-install-recommends libgbm-dev libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 libnss3
      - npm install serve --location=global
      - npm i
  build:
    commands:
      - echo Building the app
      - npm run build
      - serve -s $BUILD_DIR & npx wait-on http://localhost:3000
      - npm run cypress:run
      - pip3 install awscli --upgrade --user
      - aws s3 sync $BUILD_DIR s3://$S3_BUCKET

  post_build:
    commands:
      - echo Successfully deployed...