version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
      - npm install

  pre_build:
    commands:
      - echo Running e2e testing
      - npm run cypress:run

  build:
    commands:
      - echo Deploying the app...
      - echo This is test build

  post_build:
    commands:
      - echo Successfully deployed...

